<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN36aUjs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN36aUjs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN36aUjs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN36aUjs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerN36aUjs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'N36aUjs',
    'container.build_id' => '417bf74a',
    'container.build_time' => 1765449950,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN36aUjs');
