<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container47936yr\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container47936yr/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container47936yr.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container47936yr\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container47936yr\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '47936yr',
    'container.build_id' => '9288433e',
    'container.build_time' => 1768474987,
], __DIR__.\DIRECTORY_SEPARATOR.'Container47936yr');
