<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXbRxoA5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXbRxoA5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXbRxoA5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXbRxoA5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXbRxoA5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XbRxoA5',
    'container.build_id' => '1833cbe5',
    'container.build_time' => 1768986575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXbRxoA5');
