<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPyJmPsg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPyJmPsg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPyJmPsg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPyJmPsg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPyJmPsg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PyJmPsg',
    'container.build_id' => 'ba99b192',
    'container.build_time' => 1768911848,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPyJmPsg');
