<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Cancion extends \App\Entity\Cancion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'duracion', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'ruta', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'numeroReproducciones', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'album', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'premiumUsuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'duracion', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'ruta', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'numeroReproducciones', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'album', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'usuario', '' . "\0" . 'App\\Entity\\Cancion' . "\0" . 'premiumUsuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Cancion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremiumUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremiumUsuario', []);

        return parent::getPremiumUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremiumUsuario($premiumUsuario): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremiumUsuario', [$premiumUsuario]);

        parent::setPremiumUsuario($premiumUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlbum(): \App\Entity\Album
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlbum', []);

        return parent::getAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlbum(\App\Entity\Album $album): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlbum', [$album]);

        parent::setAlbum($album);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroReproducciones(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroReproducciones', []);

        return parent::getNumeroReproducciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroReproducciones(int $numeroReproducciones): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroReproducciones', [$numeroReproducciones]);

        parent::setNumeroReproducciones($numeroReproducciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getRuta(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRuta', []);

        return parent::getRuta();
    }

    /**
     * {@inheritDoc}
     */
    public function setRuta(?string $ruta): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRuta', [$ruta]);

        parent::setRuta($ruta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracion(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracion', []);

        return parent::getDuracion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracion(int $duracion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracion', [$duracion]);

        parent::setDuracion($duracion);
    }

}
