<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \App\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'genero', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'codigoPostal', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'cancion', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'podcast', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'album', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'artista', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'playlist'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'username', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'genero', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'fechaNacimiento', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'pais', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'codigoPostal', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'cancion', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'podcast', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'album', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'artista', '' . "\0" . 'App\\Entity\\Usuario' . "\0" . 'playlist'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername(string $username): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtista()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtista', []);

        return parent::getArtista();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtista($artista): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtista', [$artista]);

        parent::setArtista($artista);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlaylist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlaylist', []);

        return parent::getPlaylist();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlaylist($playlist): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlaylist', [$playlist]);

        parent::setPlaylist($playlist);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlbum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlbum', []);

        return parent::getAlbum();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlbum($album): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlbum', [$album]);

        parent::setAlbum($album);
    }

    /**
     * {@inheritDoc}
     */
    public function getPodcast()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPodcast', []);

        return parent::getPodcast();
    }

    /**
     * {@inheritDoc}
     */
    public function setPodcast($podcast): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPodcast', [$podcast]);

        parent::setPodcast($podcast);
    }

    /**
     * {@inheritDoc}
     */
    public function getCancion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCancion', []);

        return parent::getCancion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCancion($cancion): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCancion', [$cancion]);

        parent::setCancion($cancion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal(?string $codigoPostal): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais(?string $pais): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaNacimiento(): \DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaNacimiento', []);

        return parent::getFechaNacimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaNacimiento(\DateTime $fechaNacimiento): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaNacimiento', [$fechaNacimiento]);

        parent::setFechaNacimiento($fechaNacimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getGenero(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGenero', []);

        return parent::getGenero();
    }

    /**
     * {@inheritDoc}
     */
    public function setGenero(?string $genero): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGenero', [$genero]);

        parent::setGenero($genero);
    }

}
