<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Album extends \App\Entity\Album implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'patrocinado', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'fechaInicioPatrocinio', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'fechaFinPatrocinio', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'anyo', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'artista', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'usuario'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'titulo', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'imagen', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'patrocinado', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'fechaInicioPatrocinio', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'fechaFinPatrocinio', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'anyo', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'artista', '' . "\0" . 'App\\Entity\\Album' . "\0" . 'usuario'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Album $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo(string $titulo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', []);

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', [$usuario]);

        parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtista(): \App\Entity\Artista
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtista', []);

        return parent::getArtista();
    }

    /**
     * {@inheritDoc}
     */
    public function setArtista(\App\Entity\Artista $artista): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArtista', [$artista]);

        parent::setArtista($artista);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnyo(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnyo', []);

        return parent::getAnyo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnyo(?\DateTime $anyo): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnyo', [$anyo]);

        parent::setAnyo($anyo);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinPatrocinio(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinPatrocinio', []);

        return parent::getFechaFinPatrocinio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinPatrocinio(?\DateTime $fechaFinPatrocinio): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinPatrocinio', [$fechaFinPatrocinio]);

        parent::setFechaFinPatrocinio($fechaFinPatrocinio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicioPatrocinio(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicioPatrocinio', []);

        return parent::getFechaInicioPatrocinio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicioPatrocinio(?\DateTime $fechaInicioPatrocinio): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicioPatrocinio', [$fechaInicioPatrocinio]);

        parent::setFechaInicioPatrocinio($fechaInicioPatrocinio);
    }

    /**
     * {@inheritDoc}
     */
    public function isPatrocinado(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPatrocinado', []);

        return parent::isPatrocinado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatrocinado(bool $patrocinado): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatrocinado', [$patrocinado]);

        parent::setPatrocinado($patrocinado);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagen(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagen', []);

        return parent::getImagen();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagen(string $imagen): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagen', [$imagen]);

        parent::setImagen($imagen);
    }

}
