<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Planets extends \App\Entity\Planets implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'rotationPeriod', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'orbitalPeriod', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'diameter', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'climate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'gravity', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'terrain', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'surfaceWater', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'population', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'createdDate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'updatedDate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'url'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'rotationPeriod', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'orbitalPeriod', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'diameter', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'climate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'gravity', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'terrain', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'surfaceWater', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'population', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'createdDate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'updatedDate', '' . "\0" . 'App\\Entity\\Planets' . "\0" . 'url'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Planets $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(?string $url): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', []);

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate($updatedDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', [$updatedDate]);

        parent::setUpdatedDate($updatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate($createdDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$createdDate]);

        parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPopulation(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopulation', []);

        return parent::getPopulation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopulation(?int $population): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopulation', [$population]);

        parent::setPopulation($population);
    }

    /**
     * {@inheritDoc}
     */
    public function getSurfaceWater(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSurfaceWater', []);

        return parent::getSurfaceWater();
    }

    /**
     * {@inheritDoc}
     */
    public function setSurfaceWater(?string $surfaceWater): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSurfaceWater', [$surfaceWater]);

        parent::setSurfaceWater($surfaceWater);
    }

    /**
     * {@inheritDoc}
     */
    public function getGravity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGravity', []);

        return parent::getGravity();
    }

    /**
     * {@inheritDoc}
     */
    public function setGravity(?string $gravity): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGravity', [$gravity]);

        parent::setGravity($gravity);
    }

    /**
     * {@inheritDoc}
     */
    public function getTerrain(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerrain', []);

        return parent::getTerrain();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerrain(?string $terrain): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerrain', [$terrain]);

        parent::setTerrain($terrain);
    }

    /**
     * {@inheritDoc}
     */
    public function getClimate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClimate', []);

        return parent::getClimate();
    }

    /**
     * {@inheritDoc}
     */
    public function setClimate(?string $climate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClimate', [$climate]);

        parent::setClimate($climate);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrbitalPeriod(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrbitalPeriod', []);

        return parent::getOrbitalPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrbitalPeriod(?int $orbitalPeriod): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrbitalPeriod', [$orbitalPeriod]);

        parent::setOrbitalPeriod($orbitalPeriod);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiameter(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiameter', []);

        return parent::getDiameter();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiameter(?int $diameter): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiameter', [$diameter]);

        parent::setDiameter($diameter);
    }

    /**
     * {@inheritDoc}
     */
    public function getRotationPeriod(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRotationPeriod', []);

        return parent::getRotationPeriod();
    }

    /**
     * {@inheritDoc}
     */
    public function setRotationPeriod(?int $rotationPeriod): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRotationPeriod', [$rotationPeriod]);

        parent::setRotationPeriod($rotationPeriod);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

}
