<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Characters extends \App\Entity\Characters implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'height', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'mass', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'hairColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'skinColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'eyeColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'birthYear', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'createdDate', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'updatedDate', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'url', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'planet', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'affiliations', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'films'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'height', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'mass', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'hairColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'skinColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'eyeColor', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'birthYear', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'gender', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'createdDate', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'updatedDate', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'url', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'planet', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'affiliations', '' . "\0" . 'App\\Entity\\Characters' . "\0" . 'films'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Characters $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeight(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeight', []);

        return parent::getHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeight(?int $height): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeight', [$height]);

        parent::setHeight($height);
    }

    /**
     * {@inheritDoc}
     */
    public function getMass(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMass', []);

        return parent::getMass();
    }

    /**
     * {@inheritDoc}
     */
    public function setMass(?float $mass): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMass', [$mass]);

        parent::setMass($mass);
    }

    /**
     * {@inheritDoc}
     */
    public function getHairColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHairColor', []);

        return parent::getHairColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setHairColor(?string $hairColor): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHairColor', [$hairColor]);

        parent::setHairColor($hairColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getSkinColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSkinColor', []);

        return parent::getSkinColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setSkinColor(?string $skinColor): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSkinColor', [$skinColor]);

        parent::setSkinColor($skinColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getEyeColor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEyeColor', []);

        return parent::getEyeColor();
    }

    /**
     * {@inheritDoc}
     */
    public function setEyeColor(?string $eyeColor): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEyeColor', [$eyeColor]);

        parent::setEyeColor($eyeColor);
    }

    /**
     * {@inheritDoc}
     */
    public function getBirthYear(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBirthYear', []);

        return parent::getBirthYear();
    }

    /**
     * {@inheritDoc}
     */
    public function setBirthYear(?string $birthYear): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBirthYear', [$birthYear]);

        parent::setBirthYear($birthYear);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', []);

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender(?string $gender): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', [$gender]);

        parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedDate', []);

        return parent::getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedDate(?\DateTimeInterface $createdDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedDate', [$createdDate]);

        parent::setCreatedDate($createdDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedDate', []);

        return parent::getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedDate(?\DateTimeInterface $updatedDate): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedDate', [$updatedDate]);

        parent::setUpdatedDate($updatedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl(?string $url): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlanet(): ?\App\Entity\Planets
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlanet', []);

        return parent::getPlanet();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlanet(?\App\Entity\Planets $planet): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlanet', [$planet]);

        parent::setPlanet($planet);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliations', []);

        return parent::getAffiliations();
    }

    /**
     * {@inheritDoc}
     */
    public function addAffiliation(\App\Entity\Affiliations $affiliation): \App\Entity\Characters
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAffiliation', [$affiliation]);

        return parent::addAffiliation($affiliation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAffiliation(\App\Entity\Affiliations $affiliation): \App\Entity\Characters
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAffiliation', [$affiliation]);

        return parent::removeAffiliation($affiliation);
    }

    /**
     * {@inheritDoc}
     */
    public function getFilms(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilms', []);

        return parent::getFilms();
    }

    /**
     * {@inheritDoc}
     */
    public function addFilm(\App\Entity\Films $film): \App\Entity\Characters
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFilm', [$film]);

        return parent::addFilm($film);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFilm(\App\Entity\Films $film): \App\Entity\Characters
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFilm', [$film]);

        return parent::removeFilm($film);
    }

}
