<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTMkLaoW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTMkLaoW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTMkLaoW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTMkLaoW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTMkLaoW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TMkLaoW',
    'container.build_id' => 'e6a00e89',
    'container.build_time' => 1770290316,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTMkLaoW');
