<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOgp0ytb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOgp0ytb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOgp0ytb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOgp0ytb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOgp0ytb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ogp0ytb',
    'container.build_id' => '4a793f45',
    'container.build_time' => 1770724420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOgp0ytb');
