<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWNsYHwa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWNsYHwa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWNsYHwa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWNsYHwa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWNsYHwa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WNsYHwa',
    'container.build_id' => '4d9d29fe',
    'container.build_time' => 1770814348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWNsYHwa');
