#index:
#    path: /
#    controller: App\Controller\DefaultController::index


#UsuarioController
usuarios:
  path: /usuarios
  controller: App\Controller\UsuarioController::usuarios
  methods: [GET, POST]

usuario:
  path: /usuarios/{id}
  controller: App\Controller\UsuarioController::usuario
  methods: [GET, PUT, DELETE]

usuario_configuracion:
  path: /usuarios/{id}/configuracion
  controller: App\Controller\UsuarioController::configuracion_usuario
  methods: [GET, PUT]




#SeguirController


playlists_seguidas:
  path: /usuarios/{id}/playlists-seguidas
  controller: App\Controller\SeguirController::playlist_seguidas

seguir_borrar_playlists:
  path: /usuarios/{id}/playlists-seguidas/{idplaylist}
  controller: App\Controller\SeguirController::seguir_borrar_playlists
  methods: [ GET,PUT ]



artistas_seguidos:
  path: /usuarios/{id}/artistas-seguidos
  controller: App\Controller\SeguirController::artistas_seguidos

seguir_borrar_artistas:
  path: /usuarios/{id}/artistas-seguidos/{idartista}
  controller: App\Controller\SeguirController::seguir_borrar_artistas
  methods: [ GET,PUT ]



albums_seguidos:
  path: /usuarios/{id}/albums-seguidos
  controller: App\Controller\SeguirController::albums_seguidos

seguir_borrar_albums:
  path: /usuarios/{id}/albums-seguidos/{idalbums}
  controller: App\Controller\SeguirController::seguir_borrar_albums
  methods: [ GET,PUT ]



podcasts_seguidos:
  path: /usuarios/{id}/podcasts-seguidos
  controller: App\Controller\SeguirController::podcasts_seguidos

seguir_borrar_podcasts:
  path: /usuarios/{id}/podcasts-seguidos/{idpodcast}
  controller: App\Controller\SeguirController::seguir_borrar_podcasts
  methods: [ GET,PUT ]





  #PlanController

Plan_usuario:
  path: /usuarios/{id}/plan
  controller: App\Controller\PlanController::plan_usuario

Activar_premium:
  path: /usuarios/{id}/premium
  controller: App\Controller\PlanController::activar_premium
Pago_usuario:
  path: /usuarios/{id}/pagos
  controller: App\Controller\PlanController::pago_usuario

Suscripcion_usuario:
  path: /suscripciones/{id}
  controller: App\Controller\PlanController::suscripcion_usuario



  #PlaylistController

usuario_playlist:
  path: /usuarios/{id}/playlists
  controller: App\Controller\PlaylistController::playlist_usuario
  methods: [GET, POST]

detalles_playlist:
  path: /playlists/{id}
  controller: App\Controller\PlaylistController::detalles_playlist

canciones_playlist:
  path: /playlists/{id}/canciones
  controller: App\Controller\PlaylistController::canciones_playlist
  methods: [ GET, POST]
borrar_canciones_playlist:
  path: /playlists/{id}/canciones/{cancionid}
  controller: App\Controller\PlaylistController::borrar_canciones_playlist

playlists:
  path: /playlists
  controller: App\Controller\PlaylistController::playlists

playlist:
  path: /playlists/{id}
  controller: App\Controller\PlaylistController::playlist

#CancionController

canciones_usuario:
  path: /usuarios/1/canciones-guardadas
  controller: App\Controller\CancionController::canciones_usuario

guardar_borrar_cancion:
  path: /usuarios/1/canciones-guardadas/1
  controller: App\Controller\CancionController::guardar_borrar_cancion
  methods: [ PUT, DELETE]

canciones:
  path: /canciones
  controller: App\Controller\CancionController::canciones

cancion:
  path: /canciones/{id}
  controller: App\Controller\CancionController::cancion


#ArtistaController

artistas:
  path: /artistas
  controller: App\Controller\ArtistaController::artistas

artista:
  path: /artistas/{id}
  controller: App\Controller\ArtistaController::artista

albums_artista:
  path: /artistas/{id}/albums
  controller: App\Controller\ArtistaController::albums_artista

canciones_artista:
  path: /artistas/{id}/canciones
  controller: App\Controller\ArtistaController::canciones_artista


#AlbumController


albums:
  path: /albums
  controller: App\Controller\AlbumController::albums

album:
  path: /albums/{id}
  controller: App\Controller\AlbumController::album

canciones_album:
  path: /albums/{id}/canciones
  controller: App\Controller\AlbumController::canciones_album


#PodcastController


podcasts:
  path: /podcasts
  controller: App\Controller\PodcastController::podcasts

podcast:
  path: /podcasts/{id}
  controller: App\Controller\PodcastController::podcast

capitulos_podcast:
  path: /podcasts/{id}/capitulos
  controller: App\Controller\PodcastController::capitulos_podcast

capitulo:
  path: /capitulos/{id}
  controller: App\Controller\PodcastController::capitulo



