#index:
#    path: /
#    controller: App\Controller\DefaultController::index

usuarios:
  path: /usuarios
  controller: App\Controller\UsuarioController::usuarios
  methods: [GET, POST]

usuario:
  path: /usuarios/{id}
  controller: App\Controller\UsuarioController::usuario
  methods: [GET, PUT, DELETE]

Plan_usuario:
  path: /usuarios/{id}/plan
  controller: App\Controller\UsuarioController::plan_usuario

Activar_premium:
  path: /usuarios/{id}/premium
  controller: App\Controller\UsuarioController::activar_premium
Pago_usuario:
  path: /usuarios/{id}/pagos
  controller: App\Controller\UsuarioController::pago_usuario

Suscripcion_usuario:
  path: /suscripciones/{id}
  controller: App\Controller\UsuarioController::suscripcion_usuario

usuario_configuracion:
  path: /usuarios/{id}/configuracion
  controller: App\Controller\UsuarioController::configuracion_usuario
  methods: [GET, PUT]

usuario_playlist:
  path: /usuarios/{id}/playlists
  controller: App\Controller\UsuarioController::playlist_usuario
  methods: [GET, POST]

detalles_playlist:
  path: /playlists/{id}
  controller: App\Controller\UsuarioController::detalles_playlist

canciones_playlist:
  path: /playlists/{id}/canciones
  controller: App\Controller\UsuarioController::canciones_playlist
  methods: [ GET, POST]
borrar_canciones_playlist:
  path: /playlists/{id}/canciones/{cancionid}
  controller: App\Controller\UsuarioController::borrar_canciones_playlist




playlists_seguidas:
  path: /usuarios/{id}/playlists-seguidas
  controller: App\Controller\UsuarioController::playlist_seguidas

seguir_borrar_playlists:
  path: /usuarios/{id}/playlists-seguidas/{idplaylist}
  controller: App\Controller\UsuarioController::seguir_borrar_playlists
  methods: [ GET,PUT ]


artistas_seguidos:
  path: /usuarios/{id}/artistas-seguidos
  controller: App\Controller\UsuarioController::artistas_seguidos

seguir_borrar_artistas:
  path: /usuarios/{id}/artistas-seguidos/{idartista}
  controller: App\Controller\UsuarioController::seguir_borrar_artistas
  methods: [ GET,PUT ]


albums_seguidos:
  path: /usuarios/{id}/albums-seguidos
  controller: App\Controller\UsuarioController::albums_seguidos

seguir_borrar_albums:
  path: /usuarios/{id}/albums-seguidos/{idalbums}
  controller: App\Controller\UsuarioController::seguir_borrar_albums
  methods: [ GET,PUT ]

podcasts_seguidos:
  path: /usuarios/{id}/podcasts-seguidos
  controller: App\Controller\UsuarioController::podcasts_seguidos

seguir_borrar_podcasts:
  path: /usuarios/{id}/podcasts-seguidos/{idpodcast}
  controller: App\Controller\UsuarioController::seguir_borrar_podcasts
  methods: [ GET,PUT ]
